import type {NextPage} from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {Introduce} from "@/src/components/layout/Introduce";
import {About} from "@/src/components/layout/About";
import {Contact} from "@/src/components/layout/Contact";
import {Footer} from "@/src/components/layout/Footer";
import React from "react";
import ScrollAnimation from "@/src/components/common/ScrollAnimation";
import {Skills} from "@/src/components/layout/Skills";

const Home: NextPage = () => {


    return (
        <div>
            <Head>
                <title>My CV</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            {/*<Header/>*/}

            <main className={styles.main}>
                <Introduce/>
                <Skills/>
                <About/>
                <Contact/>
            </main>

            <ScrollAnimation/>

            <Footer/>
        </div>
    );
};

export default Home;

